# Generated by Django 4.2.26 on 2025-11-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_crud',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(default='user@gmail.com', max_length=20)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('profile_url', models.URLField()),
            ],
        ),
    ]
