# Generated by Django 4.2.26 on 2025-11-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_crud',
            name='profile_url',
            field=models.URLField(default='empty'),
        ),
    ]
