# Generated by Django 4.2.26 on 2025-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_new_crud_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_crud',
            name='profile_url',
            field=models.URLField(blank=True, default='empty', null=True),
        ),
    ]
