# Generated by Django 4.2.26 on 2025-11-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_new_crud_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_crud',
            name='profile_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
