# Generated by Django 4.2.26 on 2025-11-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_new_crud_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_crud',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='new_crud',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
