# Generated by Django 4.2.26 on 2025-11-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_new_crud_password_alter_new_crud_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_crud',
            name='password',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
